### PR TITLE
Mbarnes cluster endpoint

### PR DESCRIPTION
**Pull request by ashcrow**
Continuation of @mbarnes work on the cluster endpoint and tests.

### CODE REVIEW

**Comment by cooktheryan** [comment]
Currently hitting 
AttributeError: 'EtcdResult' object has no attribute 'node'

Example
curl -u "a:a" -X GET http://localhost:8000/api/v0/cluster/datacenter1
Traceback (most recent call last):
  File "/opt/testing/lib/python2.7/site-packages/gevent/pywsgi.py", line 854, in handle_one_response
    self.run_application()
  File "/opt/testing/lib/python2.7/site-packages/gevent/pywsgi.py", line 840, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/opt/testing/lib/python2.7/site-packages/falcon/api.py", line 182, in __call__
    responder(req, resp, **params)
  File "/home/rcook/git/commissaire/src/commissaire/handlers/clusters.py", line 170, in on_get
    self._calculate_hosts(cluster)
  File "/home/rcook/git/commissaire/src/commissaire/handlers/clusters.py", line 140, in _calculate_hosts
    for child in etcd_resp.node.children:
AttributeError: 'EtcdResult' object has no attribute 'node'

**Comment by ashcrow** [comment]
@cooktheryan good catch. I'll fix it.

**Comment by cooktheryan** [comment]
(testing)[rcook@goku commissaire]$ curl -u "a:a" -X PUT http://localhost:8000/api/v0/cluster/pickles/restart
{"status": "in_process", "finished_at": "0001-01-01T00:00:00", "started_at": "2016-01-28T14:58:19.373425", "in_process": [], "restarted": []}127.0.0.1 - - [2016-01-28 09:58:19] "PUT /api/v0/cluster/pickles/restart HTTP/1.1" 201 270 0.323161
(testing)[rcook@goku commissaire]$ curl -u "a:a" -X GET http://localhost:8000/api/v0/cluster/pickles/restart
Traceback (most recent call last):
  File "/opt/testing/lib/python2.7/site-packages/gevent/pywsgi.py", line 854, in handle_one_response
    self.run_application()
  File "/opt/testing/lib/python2.7/site-packages/gevent/pywsgi.py", line 840, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/opt/testing/lib/python2.7/site-packages/falcon/api.py", line 182, in __call__
    responder(req, resp, **params)
  File "/home/rcook/git/commissaire/src/commissaire/handlers/clusters.py", line 270, in on_get
    req.context['model'] = ClusterRestart(**json.loads(status.value))
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ashcrow** [comment]
@cooktheryan on it

**Pull request merged**
