### PR TITLE
Vagrantfile updates

### PR DESCRIPTION
**Pull request by mbarnes**
* Add the SSH key pair from `commissaire-mvp` for BDD tests.
* Rebase Vagrant boxes to Fedora 25, mostly just to stay current but also because `fedora/24-atomic-host` was unavailable.
* Use sshfs instead of nfs for folder sharing, which seems more reliable.
* Autostart `commissaire-clusterexec` service (see https://github.com/projectatomic/commissaire-service/pull/36)

### CODE REVIEW

**Comment by ashcrow** [comment]
Changes look good. I'm going to pull and try it out this afternoon.

**Comment by ashcrow** [comment]
Received this error when doing a ``vagrant up fedora-atomic``:

```
==> fedora-atomic: ===> Installing SSH keys
==> fedora-atomic: cp: 
==> fedora-atomic: cannot stat '/home/vagrant/sync/features/id_rsa'
==> fedora-atomic: : No such file or directory
==> fedora-atomic: cp: 
==> fedora-atomic: cannot stat '/home/vagrant/sync/features/id_rsa.pub'
==> fedora-atomic: : No such file or directory
==> fedora-atomic: cat: 
==> fedora-atomic: /home/vagrant/.ssh/id_rsa.pub
==> fedora-atomic: : No such file or directory
```

~~My guess is I'm missing a package (likely the sshfs one). I'm going to verify shortly but, if that is the case, I recommend adding the requirement in the docs.~~

After installing the ``vagrant-sshfs`` package I still get the same error. Is this expected?

**Comment by mbarnes** [comment]
> My guess is I'm missing a package (likely the sshfs one). I'm going to verify shortly but, if that is the case, I recommend adding the requirement in the docs.

Yeah, it's `vagrant-sshfs`.

**Comment by mbarnes** [comment]
Looks like folders are not being shared on `fedora-atomic`.  Missed that, will fix.

**Comment by mbarnes** [comment]
Hit a snag.  `fedora-atomic` does not include the package `fuse-sshfs`, and the Vagrant plugin installed by `vagrant-sshfs` wants to use `dnf` to install it.

I don't know Vagrant (or Ruby) well enough to intercept/override this yet, but a manual workaround is to log into the `fedora-atomic` host and run `sudo rpm-ostree install fuse-sshfs`, then restart the machine.  (Doing this from the Vagrantfile seems to not be soon enough.)

**Comment by mbarnes** [comment]
FYI - Manual workaround may be the best we can do for now.
```
<mbarnes> walters: are you able to use vagrant-sshfs with an atomic host?  vagrant wants
          to install fuse-sshfs with dnf.  I can "rpm-ostree install" it after the fact,
          but do you know a better way?
<walters> that's what i'm doing now
<walters> the latter i mean
<walters> at some point in the future we'll preload it in the vagrant box i think
```

**Comment by ashcrow** [comment]
The manual work around sounds fine. Mind throwing that in the doc as well?

**Comment by ashcrow** [comment]
Opened https://pagure.io/fedora-atomic/issue/38

**Comment by mbarnes** [comment]
:arrow_up: work-around documented

**Comment by ashcrow** [comment]
Verifying the workaround now.

**Comment by ashcrow** [comment]
Worked. LGTM!

**Pull request merged**
