### PR TITLE
gendocs: Use "bash strict mode" by default

### PR DESCRIPTION
**Pull request by cgwalters**
I was just browsing the code again, and since I've already contributed
to about 7 git repositories today, I figure why not make it 8!

### CODE REVIEW

**Comment by ashcrow** [comment]
Achivement

**Comment by ashcrow** [comment]
@cgwalters-bot r+ 2ce19ff7371b11e4bce269c5223fb413891c2df2

**Comment by cgwalters** [comment]
@cgwalters-bot retry

**Comment by cgwalters** [comment]
@cgwalters-bot retry

**Pull request closed without merging**
