### PR TITLE
doc: Updates for new commissaire-http cli code.

### PR DESCRIPTION
**Pull request by ashcrow**
Doc updates for https://github.com/projectatomic/commissaire-http/pull/6

### CODE REVIEW

**Comment by ashcrow** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;oF65DFD2&#x2F;463-3-multi-host-mgr-2-port-server-script"> (3) [multi-host-mgr-2] Port server script</a>

**Comment by ashcrow** [comment]
@cooktheryan ping

**Comment by mbarnes** [comment]
I can take this if you need me to.

**Comment by ashcrow** [comment]
@mbarnes go ahead and steal it from @cooktheryan.

**Review by mbarnes — APPROVED** [review]
All looks good to me.

I wonder if it would be worth the time to automate these "automodule" files for submodules so we don't have to keep manually updating them.  They're all uniform, doesn't seem too difficult.

**Pull request merged**
