### PR TITLE
tools: Added script to generate changelog

### PR DESCRIPTION
**Pull request by ashcrow**
Quick changelog generation script to help with releases.

### CODE REVIEW

**Comment by mbarnes** [comment]
Script seems to work, but how do you envision it being used as part of releases?

**Comment by ashcrow** [comment]
@mbarnes I imagine each repo having a ``CHANGELOG.md`` for their own changes. Nothing crazy.

**Comment by mbarnes** [comment]
What about the content?  List changes since the previous release, and replace it for each release?  Or append to it for each release so we have a "complete" history?

Just trying to figure out what you had in mind...

**Comment by ashcrow** [comment]
Append for each release. The tool *should* keep the latest release on top at all times.

**Review by mbarnes — APPROVED** [review]

**Pull request merged**
