### PR TITLE
[merged] cli: Removed CLI scripts and tests.

### PR DESCRIPTION
**Pull request by ashcrow**
CLI items will now live in it's own package.

### CODE REVIEW

**Comment by mbarnes** [comment]
:+1:

I assume we'll keep the client setup docs in the server package?  Seems best to keep all the docs together.

**Comment by ashcrow** [comment]
@mbarnes yes. Keeping the docs in the server makes the most sense to me right now.

**Comment by ashcrow** [comment]
For posterity here is the successful move commit: https://github.com/projectatomic/commctl/commit/0877a2ffefe8c8c3eaeed01409152056fbe495b5

**Comment by mbarnes** [comment]
@cgwalters-bot r+

**Pull request closed without merging**
