### PR TITLE
Add more tags to hosts.feature.

### PR DESCRIPTION
**Pull request by mbarnes**
Just to help me isolate host creation cases for an ongoing investigation.

### CODE REVIEW

**Comment by ashcrow** [comment]
@rh-atomic-bot try

**Comment by mbarnes** [comment]
I can rebase this on https://github.com/projectatomic/commissaire/pull/143 if needed.

**Comment by ashcrow** [comment]
@mbarnes it might be a flake. The error was in connecting to etcd. I'm rerunning it now to check.

**Comment by ashcrow** [comment]
Yeah it was a flake ... etcd went sideways on the Travis infrastructure.

**Comment by ashcrow** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
