### PR TITLE
Adds a basic CLI component

### PR DESCRIPTION
**Pull request by ashcrow**

### CODE REVIEW

**Comment by ashcrow** [comment]
Lost a comment in the force push ...

@mbarnes I hear the ```new``` versus ```create``` argument and it makes sense to me. I'd like to hold off a little bit on make a decision on renaming though. I could see a similar thing said for host where you are technically not creating a host but it's a new host. I can also see ```start``` be an option for upgrade and restart as it seems to make better sense than ```create``` as well.

**Comment by mbarnes** [comment]
Fair enough.  Lots of potential bikeshedding there.

**Comment by ashcrow** [comment]
@mbarnes FWIW I do agree ```create``` probably won't be kept for the items you pointed out. It was a good note and I didn't think about it until you brought it up.

**Comment by ashcrow** [comment]
I'll fix the merge conflicts shortly.

**Comment by mbarnes** [comment]
Squashed and merged.

One trivial merge conflict in `setup.py`.  I took care of it.

**Pull request closed without merging**
