### PR TITLE
[merged] Added a Vagrant config for Kubernetes

### PR DESCRIPTION
**Pull request by ashcrow**
Since I was looking at the Kubernetes API stuff for a spike I went ahead and took care of adding a simple Kubernetes box. Two birds and what not.

### CODE REVIEW

**Comment by mbarnes** [comment]
Looks good.  :+1:

Does `development.rst` need updating?  (the bit where it mentions `vagrant up --parallel`)

**Comment by ashcrow** [comment]
@mbarnes good point. I should note it is available there. One fix up incoming.

**Comment by ashcrow** [comment]
Did it in a doc commit instead.

**Comment by mbarnes** [comment]
:+1:

@rh-atomic-bot r+

**Pull request closed without merging**
