### PR TITLE
Update support for etcd with tls

### PR DESCRIPTION
**Pull request by intlabs**
This pull request:
- Unifies etcd config options to use _ between words their names
- Adds the option for a custom CA cert

For etcd v3 to work correctly the current python-etcd from git is required: https://github.com/jplana/python-etcd/commit/0d0145f5e835aa032c97a0a5e09c4c68b7a03f66

### CODE REVIEW

**Comment by ashcrow** [comment]
bot, test pull request once

**Review by mbarnes — CHANGES_REQUESTED** [review]
Changes look okay, but I suggest rearranging your commits so the change history is easier to follow.  Do the dash-to-underscore conversions in the existing code first, then just use underscores in your follow up commits.

**Comment by intlabs** [comment]
I'm afraid my git-fu has failed me - and I've only managed to convert to a single commit. I hope this is ok - I'll make sure that in future I don't include junk commits.

**Comment by ashcrow** [comment]
@intlabs I think that will work for this PR. Out of curiosity, did you try `git rebase -i $YOUR_LAST_COMMIT^` when reordering?

**Comment by mbarnes** [comment]
@intlabs There were no junk commits, just the sequence was a little weird.  But I don't want to be too pedantic; what I was asking does require some git-fu.  I'll take the single commit if you could amend your commit message with a note about changing the dashes (`git commit --amend`).

**Review by mbarnes — APPROVED** [review]
That looks good.  Thanks!

**Pull request merged**
