### PR TITLE
doc: Removed old greenlet/clusterexec items.

### PR DESCRIPTION
**Pull request by ashcrow**

### CODE REVIEW

**Comment by mbarnes** [comment]
@rh-atomic-bot r+

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot clean

**Comment by cgwalters** [comment]
I think unfortunately things are a bit wedged...I might be able to fix it manually, but it seems simpler to close this PR and reopen another?

**Comment by mbarnes** [comment]
Tests passed so I'll just merge this one manually.

Can try again with https://github.com/projectatomic/commissaire/pull/122

**Pull request merged**
