### PR TITLE
Hack around early cloud-init script

### PR DESCRIPTION
**Pull request by mbarnes**
This might be racy on some systems, but I don't have any better ideas at the moment.

The cloud-init script registers the host to Commissaire during bootup before the host is ready to accept SSH connections, causing the bootstrap playbook to fail.

Retry a few times when Ansible says the host is unreachable.

### CODE REVIEW

**Comment by ashcrow** [comment]
@mbarnes I'm ok with this idea. I agree it could be a little racy and, if/when we do more than one host at a time it could cause hosts to call bootstrap multiple times. One other possible way this might be 'fixed' is if there is a way that we can wait until ```sshd.service``` has started, maybe hold for a few seconds and *then* call out to bootstrap. What do you think of that idea? Keep in mind, if my proposal could work it does not stop us from still allowing retries as done in this PR.

**Comment by mbarnes** [comment]
@ashcrow Something like that did occur to me, but this being a corner case I assumed we wouldn't want to ***always*** have some arbitrary delay before bootstrapping.  (Then again, maybe it doesn't really matter?)

A variation of this could be to add an optional `'bootstrap_delay'` parameter to the `PUT` data:
```
    {
      "cluster": "default",
      "ssh_priv_key": "dGVzdAo...",
      "bootstrap_delay": 10
    }
```
But either way still leaves us guessing at an appropriate timeout.

**Comment by ashcrow** [comment]
@mbarnes true. Based on your testing am I right in thinking that once```sshd.service``` is running we should be OK to bootstrap? Maybe we don't **have to have** the delay?

I'll defer to you to choose which option you think is best here :smile:.

**Comment by mbarnes** [comment]
@ashcrow Right, the problem is just that `cloud-init.service` runs before `sshd.service`, and without some sort of server-side delay the bootstrap always fails with a "host unreachable" status for me.

If this feature didn't have to work with a gold image I could think of more reliable ways to solve it (e.g. add a systemd unit that depends on `sshd.service`).

I guess for now the retry loop seems the least intrusive to me, but we can certainly revisit this.

**Comment by ashcrow** [comment]
@mbarnes ok let's give it a go.

@cgwalters-bot try

**Comment by ashcrow** [comment]
@cgwalters-bot r+

**Pull request closed without merging**
