### PR TITLE
[merged] Rdgo build

### PR DESCRIPTION
**Pull request by cgwalters**
Note this doesn't get it to *run*, but it's a start.

### CODE REVIEW

**Comment by ashcrow** [comment]
@cgwalters-bot try

**Comment by ashcrow** [comment]
I generally like to have the changelog in the spec updated when it changes but I don't think it's worth requesting that for this change. We'll add it in (cc @mbarnes).

**Comment by ashcrow** [comment]
@cgwalters-bot r+

**Comment by cgwalters** [comment]
FWIW rpmdistro-gitoverlay always unilaterally deletes the RPM changelog because I think what it covers should be split between `git log` and something like Bodhi.

**Pull request closed without merging**
