### PR TITLE
[merged] Remove workarounds, etc for Python 2.6 compatibility.

### PR DESCRIPTION
**Pull request by mbarnes**
Just some cleanup.

### CODE REVIEW

**Comment by mbarnes** [comment]
Weird, why didn't the tests trigger?  Doesn't like branch names that start with a number?

**Comment by ashcrow** [comment]
That is odd ....

**Comment by ashcrow** [comment]
Looks like there is a [logging config error with BDD](https://travis-ci.org/projectatomic/commissaire/builds/134569471#L880-L885).

**Comment by ashcrow** [comment]
LGTM

@rh-atomic-bot try

**Comment by ashcrow** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
