### PR TITLE
Secret models

### PR DESCRIPTION
**Pull request by mbarnes**

### CODE REVIEW

**Comment by ashcrow** [comment]
I know this is still WIP but here are the e2e tests that failed:

```
  features/hosts/create.feature:35  Recreating a compatible host with authentication
  features/hosts/create.feature:43  Recreating an incompatible host with authentication
  features/hosts/retrieve.feature:49  Retrieve existing host with authentication
```

**Comment by mbarnes** [comment]
> I know this is still WIP but here are the e2e tests that failed:

Yeah, that's expected until the other PRs get merged.
(https://github.com/projectatomic/commissaire-http/pull/77, https://github.com/projectatomic/commissaire-service/pull/65)

All tests pass locally here.

**Comment by mbarnes** [comment]
@ashcrow  Any objection to me merging these secret model PRs now?  They seem self-contained, and I'd rather push separate PRs with my own additional work.  I've reviewed these already since it's your code.

**Comment by ashcrow** [comment]
@mbarnes no objection.

**Pull request merged**
