### PR TITLE
Monkeying around with OSCmdBase

### PR DESCRIPTION
**Pull request by mbarnes**
This isn't a real pull request yet.  Just wanted to run a couple ideas by you related to allowing extra commands in `oscmd`.

The first commit is a simplification of sorts.  Since none of the `oscmd` classes have instance data I converted all the methods to `@classmethod` so we don't have to instantiate these things.

The second commit is a simple hack for tacking on extra commands.  I'm not sure exactly how this enhancement is meant to be used so it's kind of a guess.

### CODE REVIEW

**Comment by mbarnes** [comment]
Yeah, I wasn't sure if you intended this more for standalone one-off commands for special cases or as extra instructions to run before/after the defined command methods.

What I had in mind with the dictionary keys is to implement a template pattern in the ansible logic.  Where instead of writing it out as "if the OS is RHEL then enable specific repos" it would be more like "if this OS defines commands to enable specific repos, do so now" (by way of checking for a particular dictionary key like `'enablerepos'`).

I realize this is very minimal and open-ended.  It would help to know any more specific use cases you had in mind.

**Comment by ashcrow** [comment]
@mbarnes really the only use case came from RHEL needing to subscribe to repositories before it could continue the process. @cooktheryan came up with the idea of having it added to ```OSCmd``` which, at the time, would have been the only obvious place to put the code. It does still make sense but there are also other options now if we decide to use them.

I could easily see extra commands being needed on other OS's though in the future. But as of right now the only case we have for it is RHEL.

**Comment by cooktheryan** [comment]
+1 with what @ashcrow stated about one of the only pre use cases is for RHEL but would be nice to have the ability for all in the future. I do really like the pre/post idea @mbarnes had but as a step 1 it would be really nice to address the subscribe to RHEL repositories issue before installing docker, flannel, and kube because it removed the need for the developer/admin to track down what repos are required.

**Comment by mbarnes** [comment]
So the full solution for this bootstrap case would be to prepend a new command for enabling repos to the `bootstrap.yaml` playbook and then set a `play_vars` entry in `ansibleapi.py`to either a no-op like `/usr/bin/true` or an actual repo command, depending on the OS.

Is that right?

Honestly for now I think I'd just hardcode the commands in `ansibleapi.py` (maybe with a `FIXME` comment) until we have a second use case.  It's hard to generalize from one data point.

Or we could rough in something really simple and stupid, like what I did, to handle this one case and later refine it as requirements demand.

I feel like anything more at this point would be over-engineering.

**Comment by ashcrow** [comment]
@mbarnes I'm fine with that. I trust your POV :smile:.

**Comment by mbarnes** [comment]
Okay then I'll merge the first commit and hit the bootstrapping case directly in a separate PR.

**Comment by ashcrow** [comment]
@mbarnes sounds good!

**Comment by ashcrow** [comment]
Is this still an inprocess PR or did #59 overtake it?

**Comment by mbarnes** [comment]
No it isn't.  Closing.

I linked to this discussion in the patch for https://github.com/projectatomic/commissaire/pull/59.

**Pull request closed without merging**
