### PR TITLE
[WIP] Try using a thread pool for Ansible jobs

### PR DESCRIPTION
**Pull request by mbarnes**
To summarize, this replaces the `InvestigatorPlugin` with a `JobsPlugin` which just provides global access to a thread pool where async jobs can be submitted.

The thread pool I'm using is pretty cheap but it's what's available in Python 2's standard library.  I didn't want to go adding a new dependency just yet.  The thread pool is actually a process pool (`multiprocessing.pool`) except the processes are actually threads (`multiprocessing.dummy`)... so not exactly a feature-rich implementation.

I changed the investigator job to not loop, so it's always run-once.

The `pool.apply_async()` method takes an optional callback object, which I'm not using at the moment but I was thinking it might be a better (safer?) way to update job status and any internal bookkeeping after the Ansible job finishes.  Unfortunately because the thread pool is a process pool, the only result data the job can (easily) return is a success/fail flag.

Suffice it to say, this is still heavily WIP.

### CODE REVIEW

**Comment by mbarnes** [comment]
@ashcrow You might think about what to do with the `/api/v0/status` endpoint because it's no longer accurate with these changes.  We could perhaps replace the `investigator` stanza with something showing the current state of the whole thread pool.

I don't have any more substantial changes atm, just trying to fix up the unit tests and then do a bunch of manual testing with my local cluster.  Help there is also appreciated.

**Comment by mbarnes** [comment]
Tests are working, but using this with actual hosts is not.

The fact that the Ansible module is using `multiprocessing.Process` may doom this effort, since it would mean the Ansible subtask now also has our thread pool and that appears to be causing all kinds of problems.

I suppose I could try using an actual process pool and see if that helps at all with the child process cleanup, which is what instigated all this.

Frustratingly, Python 3.4 appears to offer a solution with `multiprocessing.set_start_method('spawn')` [1] which is a global configuration to spawn a fresh new interpreter instead of forking the current one (along with all its state, threads, etc.).

[1] https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method

**Comment by mbarnes** [comment]
Tried using a process pool (`multiprocess.Pool`) but got stymied there too.  The worker processes in the pool have their daemon flag set and daemon processes are not allowed to spawn child processes, which is exactly what Ansible needs to do.

I keep encountering technical problems that are supposedly solved in Python 3, but getting Python 2 to cooperate has proven more difficult.  I think I might set this aside and move on to more productive work.

One thing I *am* taking away from this is I really don't think the subprocesses we spawn should be relying on CherryPy (or any parent resources) in any way.  It's just really brittle.  I've already had to work around it in the `investigator` function in `master` and I've been fighting with it a lot on this branch.  I worry the same issues are going to impede implementing [CPD-126] (https://github.com/projectatomic/commissaire/wiki/cpd-126).  A safer approach would be for subprocesses to reuse or create their own `StoreHandler` instance and call its methods directly.

**Comment by ashcrow** [comment]
One of the ideas I was toying with a few weeks back was using `multiprocessing` with a manager or proxy  https://docs.python.org/2/library/multiprocessing.html#sharing-state-between-processes. Any thoughts about going down that road instead of using parent resources directly?

**Comment by mbarnes** [comment]
Offhand and without really knowing what you had in mind, it seems to me like etcd mostly covers what `multiprocessing.Manager` gets you for shared data.  Can you elaborate?

I had the thought of maybe adding a `clone()` method to the `StoreHandler` proposal, which would replicate all the configuration but without any connection state or anything else that can't be pickled.  Connection-less cloned instances could then be safely passed to subprocesses where they create their own connections as needed.  I think that's about all the shared state we need at present, no?

**Comment by ashcrow** [comment]
@mbarnes Hrm, you're right. I honestly might be overthinking it.

**Comment by ashcrow** [comment]
@mbarnes do you mind taking a swag at creating a card for passing around connection details? I think we should do that work before we jump into cpd-126. As long as we do it before hand I think cpd-126 won't need modifications.

**Comment by mbarnes** [comment]
@ashcrow Sure, I was just thinking about that this morning.

I think I misspoke slightly above: what we actually need is a container class for `StoreHandler` instances, separate from the `CherryPyStorePlugin` itself but with the same API.  *That's* the thing that needs a `clone()` method and passed to subprocesses.  So the CherryPy plugin in the main process would just be a trivial passthrough to this thing.

**Comment by ashcrow** [comment]
OK. WFM. I'll review the card once done to make sure I totally understand.

**Comment by mbarnes** [comment]
https://trello.com/c/9lOa0Zcm/

Kinda hand wavy and subject to change until I get to actually coding this, but that card captures at least my initial idea.

**Comment by mbarnes** [comment]
Also, for the record, another thing to fall out of this PR: https://trello.com/c/owiNJomu

**Comment by ashcrow** [comment]
> https://trello.com/c/9lOa0Zcm/
>
>Kinda hand wavy and subject to change until I get to actually coding this, but that card captures at least my initial idea.

It makes sense to me. I modified it a tiny bit noting that the class proposed sounds like it would be `StoreHandlerManager`. I  generally have disliked `Manager` patterns :laughing: but I think it makes sense for this.

I'm going to go ahead and close this PR.

**Pull request closed without merging**
