### PR TITLE
Document cloud-init integration

### PR DESCRIPTION
**Pull request by mbarnes**
Getting the hang of ReStructuredText formatting...

### CODE REVIEW

**Comment by ashcrow** [comment]
Content is good. I think it would make sense to cross link the bootstrap documentation to this page with a note stating cloud-init is a way to bootstrap.

**Comment by mbarnes** [comment]
:arrow_up:  Struggled with the wording for some reason.  How's this?

**Comment by ashcrow** [comment]
:+1:

**Comment by ashcrow** [comment]
@cgwalters-bot rollup

**Comment by ashcrow** [comment]
rollup-

**Comment by ashcrow** [comment]
@cgwalters-bot rollup-

**Comment by ashcrow** [comment]
@cgwalters-bot r+

**Pull request closed without merging**
