### PR TITLE
[merged] More investigator changes

### PR DESCRIPTION
**Pull request by mbarnes**
I figured out why `self.process.terminate()` was failing and I now understand how a child process was still able to use CherryPy's plugins.  (Maybe you understood the latter part already but I'm caught up now.)

See the code comment.

However, knowing the investigator process is running a complete copy of the main process (threads and all) makes me pretty nervous.  I think we're in for other weird side-effects like the terminate issue.

I'm wondering if the investigator job might work better as a long-running thread instead of a child process since it sits in a loop forever once started, and we could just switch from `multiprocessing.Queue` to `queue.Queue`.

I vaguely recall when we were porting to CherryPy you had some rationale -- written down somewhere, I believe -- for spawning child processes instead of threads for the Ansible jobs due to CherryPy's (or maybe Python's) architecture, but I can't find or remember it now.

Am I remembering that correctly?

Don't yet know if this is related to https://github.com/projectatomic/commissaire/issues/141 or https://github.com/projectatomic/commissaire/issues/142.

### CODE REVIEW

**Comment by ashcrow** [comment]
We had a problem with `greenlet` and `multiprocessing`. I had found that the compromises needed to make Ansible (which uses `multiprocessing`) work with `greenlet`s didn't make sense. At the time we were using `gunicorn` which was `greenlet` based so it made sense to switch to a `thread` or `multiprocessing` based server ... of which `CherryPy` ended up being the choice.

I believe we could run `Ansible` via `threading` with little to no issues. Another possible fix would be to use `multiprocessing`'s proxy system to share resources in subprocesses.

**Comment by ashcrow** [comment]
@rh-atomic-bot try

**Comment by ashcrow** [comment]
@mbarnes I am very interested in your thoughts as to which path would make more sense to you. I am leaning towards one but would rather hear yours before hand as to not taint your view towards mine accidentally 😄.

**Comment by mbarnes** [comment]
@ashcrow My strongest preference is for a thread-based solution, perhaps even using a thread pool to service both `investigator` and `clusterexec` jobs.  I'm playing around with some ideas over the weekend to see if it's feasible.

**Comment by ashcrow** [comment]
@mbarnes ok sounds good. Any reason for me to wait to approve this PR?

**Comment by mbarnes** [comment]
No, it's a needed correction for what we currently have... even if it all changes shortly.

**Comment by ashcrow** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
