### PR TITLE
Model validation

### PR DESCRIPTION
**Pull request by ashcrow**
Requires https://github.com/projectatomic/commissaire/pull/169

### CODE REVIEW

**Comment by mbarnes** [comment]
@ashcrow Can you rebase this on `master`?  The previous PR is mixed in here.

**Comment by mbarnes** [comment]
Relevant commits look good.  Out of curiosity, did you consider using `jsonschema`?  It looks like it covers a lot of the same ground for JSON validation.

https://pypi.python.org/pypi/jsonschema

**Comment by ashcrow** [comment]
> @ashcrow Can you rebase this on master? The previous PR is mixed in here.

Working on it now

In terms of ``jsonschema`` I did not. Might be worth migrating in the near future.

**Comment by mbarnes** [comment]
Travis still not happy today.  Failing on a `PicklingError` but I don't think that's our code.

**Comment by ashcrow** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;AYcMkxxn&#x2F;372-2-multi-host-mgr-add-model-validation"> (2) [multi-host-mgr] Add model validation</a>

**Comment by mbarnes** [comment]
Ran all tests locally and merged.

**Pull request merged**
