### PR TITLE
[merged] Fix restart false positive

### PR DESCRIPTION
**Pull request by ashcrow**
Fixes issue where restarts would report failed even though they worked as expected.

Work based on #160 and will need to be rebased.

### CODE REVIEW

**Comment by ashcrow** [comment]
Rebased on master.

**Comment by mbarnes** [comment]
What's the `"sleep 2"` for?

Is that just a fudge to keep Ansible from misreporting an unreachable error?

**Comment by ashcrow** [comment]
@mbarnes unfortunately yes :laughing: https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back

**Comment by mbarnes** [comment]
Ah, that's useful.  Could you add that link to the commit message just as a historical artifact?

**Comment by ashcrow** [comment]
Sure.

**Comment by ashcrow** [comment]
:up

**Comment by mbarnes** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
