### PR TITLE
[merged] Relicense to GPLv3+

### PR DESCRIPTION
**Pull request by ashcrow**
- Changes license from AGPLv3+ to GPLv3+
- Adds license sections to the docs

### CODE REVIEW

**Comment by ashcrow** [comment]
There is a lot of file changes here. It should be only license text changes in the first commit. The second should be documentation additions. Please double check I didn't miss anything :smile:.

**Comment by mbarnes** [comment]
Assuming there was a valid reason for having both `COPYING` and `LICENSE` in the repo, could we just make one a symlink to the other?

**Comment by mbarnes** [comment]
Looks like you got everything.   :+1:
```
$ git grep -il Affero
COPYING
LICENSE
```

**Comment by mbarnes** [comment]
I verified `Affero` no longer appears in the code.  There's a few more files that *maybe* should have a license blurb but I'm not sure.  What do you think?

 * The `.feature` files under `features/`?
 * The Ansible playbooks?

**Comment by ashcrow** [comment]
I have no strong feelings over symlink instead of the full file. Good call on feature files. I'll update after lunch.

**Comment by mbarnes** [comment]
I don't either, I just thought it would ensure they stay in sync.

**Comment by ashcrow** [comment]
:arrow_up:

**Comment by mbarnes** [comment]
Additional commits look good.

I feel a little more strongly about the symlinking having found this: https://github.com/projectatomic/atomic/commit/2ea7554d4fa9e553f7cb88cf7e0c08f0ed6b0558

Would you mind that?

**Comment by ashcrow** [comment]
@mbarnes I'll go ahead and do it.

**Comment by ashcrow** [comment]
:arrow_up:

**Comment by mbarnes** [comment]
@cgwalters-bot try

**Comment by mbarnes** [comment]
@cgwalters-bot r+

**Pull request closed without merging**
